service: realtimechat

provider:
    name: aws
    ecr:
    images:
      appimage:
        path: ./
    logs:
    websocket:
      level: ERROR
    runtime: nodejs14.x
    profile: serverlessUser
    region: us-east-1
    environment:
        tableName: ${self:custom.tableName}
    iamRoleStatements:
        - Effect: Allow
          Action:
           - "execute-api:ManageConnections"
          Resource:
            - "arn:aws:execute-api:*:*:**/@connections/*"
        - Effect: Allow
          Action:
              - dynamodb:*
          Resource: '*'

    websocketApiRouteSelectionExpression: $request.body.action


plugins:
  - serverless-offline
  - serverless-dynamodb-local

custom:
    tableName: WebsocketUsers
    dynamodb:
      start:
        migrate: true
    serverless-offline:
        host: 0.0.0.0

functions:
    websocket-connect:
        handler: lambdas/websockets/connect.handler
        events:
            - websocket:
                  route: $connect
    websocket-disconnect:
        handler: lambdas/websockets/disconnect.handler
        events:
            - websocket:
                  route: $disconnect
    websocket-default:
        handler: lambdas/websockets/default.handler
        events:
            - websocket:
                  route: $default
    websocket-message:
        handler: lambdas/websockets/message.handler
        events:
            - websocket:
                  route: message


resources:
    Resources:
        WeboscketUserTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.tableName}
                AttributeDefinitions:
                    - AttributeName: ID
                      AttributeType: S
                KeySchema:
                    - AttributeName: ID
                      KeyType: HASH
                BillingMode: PAY_PER_REQUEST
                SSESpecification:
                   SSEEnabled: True
                StreamSpecification:
                   StreamViewType: NEW_IMAGE